version: '3'
services:

  logstash:
    build: ./logstash
    ports:
      - 5002:5002
      - 5001:5001
      - 5000:5000
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m

  elasticsearch:
    image: iromu/elasticsearch:latest
    ports:
      - "9200:9200"
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx2048m -Xms2048m"

  kibana:
    image: iromu/kibana:latest
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch


