version: '3'
services:

  logstash:
    build: ./logstash
    ports:
      - 5001:5001
      - 5000:5000
    links:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m

  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx2048m -Xms2048m"

  kibana:
    build: ./kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch

