FROM docker.elastic.co/kibana/kibana:6.1.1

ADD config/kibana.yml /usr/share/kibana/config/

#RUN mkdir -p /opt/kibana/config
#COPY ./config/kibana.yml /opt/kibana/config
#RUN su - kibana -c "/usr/share/kibana/bin/kibana-plugin install x-pack"
